### ISSUE TITLE
PfxImport:  Cannot validate argument on parameter Thumbprint

### ISSUE THREAD

**Issue by ruandersMSFT** [dsccommunity/CertificateDsc#218]
#### Details of the scenario you tried and the problem that is occurring

Importing DigiCert Wildcard / GeoTrust RSA CA 2018 certificate fails with "Cannot validate argument on parameter Thumbprint: System.InvalidOperationException: '‎c0ba334eb65b7942e9c57c116a804dc44a269a28' is 
not a valid hash. 

#### Verbose logs showing the problem

![image](https://user-images.githubusercontent.com/16927960/75617461-9d084c00-5b1c-11ea-95d8-8686776cf29a.png)

VERBOSE: [localhost]:[SP201902]: LCM:  [ Start  Set      ]
VERBOSE: [localhost]:[SP201902]: LCM:  [ Start  Resource ]  [[PfxImport]PfxImport_]
VERBOSE: [localhost]:[SP201902]: LCM:  [ Start  Test     ]  [[PfxImport]PfxImport_]
VERBOSE: [localhost]:[SP201902]: LCM:  [ End    Test     ]  [[PfxImport]PfxImport_]  in 1.4690 seconds.
PowerShell DSC resource MSFT_PfxImport  failed to execute Test-TargetResource functionality with error message: Cannot 
validate argument on parameter 'Thumbprint'. System.InvalidOperationException: '‎c0ba334eb65b7942e9c57c116a804dc44a269a28' is 
not a valid hash. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : [localhost]
 
#### Suggested solution to the issue

Review/resolve code.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
PfxImport ('PfxImport_' + $Certificate.CertThumbprint) {
                Ensure = $Certificate.Ensure
                Thumbprint = $Certificate.Thumbprint
                Path = $Certificate.DestinationPath
                Location = $Certificate.Location
                Store = $Certificate.Store
                Credential = $objCertCredential
                Exportable = $Certificate.Exportable
            }
```

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 1909
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running

Name                           Value                                                                                          
----                           -----                                                                                          
PSVersion                      5.1.18362.628                                                                                  
PSEdition                      Desktop                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                        
BuildVersion                   10.0.18362.628                                                                                 
CLRVersion                     4.0.30319.42000                                                                                
WSManStackVersion              3.0                                                                                            
PSRemotingProtocolVersion      2.3                                                                                            
SerializationVersion           1.1.0.1   
#### Version of the DSC module that was used ('dev' if using current dev branch)

4.7.0.0

**Comment by ruandersMSFT** [comment]
Added verbose logging to view comparison, trying to determine why it doesn't match when Hex Length 40.

![image](https://user-images.githubusercontent.com/16927960/75629118-8570a800-5b9c-11ea-8777-b96b768acf3d.png)

**Comment by ruandersMSFT** [comment]
```powershell
if ("‎C0BA334EB65B7942E9C57C116A804DC44A269A28" -cmatch "^[a-fA-F0-9]{40}$")
{
    Write-Host "Match!" -ForegroundColor Green
}
else
{
    Write-Host "Not a Match!" -ForegroundColor Red
}

```

Yields no match:

![image](https://user-images.githubusercontent.com/16927960/75629190-03cd4a00-5b9d-11ea-9134-b78c43921890.png)

**Comment by PlagueHO** [comment]
Hi @ruandersMSFT - I've found the issue. When you copy the Thumbprint of a certificate out of Windows Certificate Manager, it seems to include an extra character at the beginning (something to do with char encoding). 

If I Copy/Paste the code you put in above into a PowerShell window it shows like this:
![image](https://user-images.githubusercontent.com/7589164/75638712-2a20e180-5c92-11ea-9e86-36fda86dabde.png)

So delete the 'C' at the beginning and add it back in.

**Comment by ruandersMSFT** [comment]
Verified, resolved.

**Comment by shcrist** [comment]
Ran into the same issue. Copy/Paste from cert manager added a special character. Took action recommended by PlagueHO about and it resolved the issue.
