### ISSUE TITLE
PfxImport & CertificateImport: Add base64 content parameter for PFX and certificate import resources

### ISSUE THREAD

**Issue by 39Delta** [dsccommunity/CertificateDsc#241]
#### Details of the scenario you tried and the problem that is occurring
[Enhancement] Provide a parameter for the import resources that contains the certificate content as a base64 string that can then be used to set the file content temporarily for import.  File would be created and removed only on SET when ensure is present and only if the optional 'Base64Content' parameter is used.  Otherwise the resource works as it does today.  Effectively storing the CER and PFX in the MOF.

#### Suggested solution to the issue
Update the resources that import public certificates and PFX to support a parameter that can contain the base64 encoded value for either a certificate or PFX.

**Comment by 39Delta** [comment]
I have included a PR for if and when this issue is accepted.  
https://github.com/dsccommunity/CertificateDsc/pull/242

**Comment by PlagueHO** [comment]
Hi @39Delta - great feature! I'll review once the tests are passing over on the PR. Great stuff!

**Comment by 39Delta** [comment]
Thanks @PlagueHO, I have pushed updates to fix tests.  Thanks for your time!

**Comment by 39Delta** [comment]
Hi @PlagueHO, I am testing a change to this approach where the contents are not written to the file system and instead are imported directly as a byte array into the certificate object before being added to the cert store.  I will push the updates when complete.  Thanks!

**Comment by PlagueHO** [comment]
Awesome! Looking forward to getting this in @39Delta - thanks for working on this!

**Comment by PlagueHO** [comment]
Completed by #242
